---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-slim
# description will be included in the image's metadata
description: Universal Blue for limited-memory systems

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - ModemManager
      - NetworkManager-adsl
      - NetworkManager-openconnect-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-ppp
      - NetworkManager-ssh-gnome
      - NetworkManager-vpnc-gnome
      - NetworkManager-wwan
      - budgie-backgrounds
      - budgie-control-center
      - budgie-desktop
      - budgie-desktop-defaults
      - budgie-desktop-view
      - budgie-screensaver
      - dconf
      - fprintd-pam
      - gedit
      - glib-networking
      - glx-utils
      - gnome-bluetooth
      - gnome-color-manager
      - gnome-disk-utility
      - gnome-keyring-pam
      - gnome-settings-daemon
      - gnome-system-monitor
      - gnome-terminal
      - gvfs-afc
      - gvfs-afp
      - gvfs-archive
      - gvfs-fuse
      - gvfs-goa
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-smb
      - lightdm
      # replaced by ublue-base
      # - mesa-dri-drivers
      # - mesa-vulkan-drivers
      - nemo
      - nemo-fileroller
      - nemo-seahorse
      - network-manager-applet
      - plasma-discover
      - plymouth-system-theme
      - polkit
      - seahorse
      - slick-greeter
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-user-dirs-gtk
      - xorg-x11-drv-amdgpu
      - xorg-x11-drv-ati
      - xorg-x11-drv-evdev
      - xorg-x11-drv-libinput
      - xorg-x11-drv-nouveau
      - xorg-x11-drv-qxl
      - xorg-x11-drv-wacom
      - xorg-x11-server-Xorg
      - xorg-x11-xauth
      - xorg-x11-xinit
      - xorg-x11-drv-intel
      - xorg-x11-drv-openchrome
      - xorg-x11-drv-vmware

      - fedora-release-budgie-atomic
      - gnome-software-rpm-ostree
      - xorg-x11-server-Xwayland

      - gnome-terminal
      - emacs
      - emacsclient
      - vim
      - htop
      - micro
      - starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

